version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
      - "8765:8765"
    volumes:
      - ./src:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - OPENAI_API_KEY=${OPENAI_API_KEY}